const WeddingGuests = [
  { name: "Tasso de Mattos", group: "A" },
  { name: "Jacqueline de Mattos", group: "A" },
  { name: "Juliana Mattos", group: "A" },
  { name: "Denise Mattos", group: "B" },
  { name: "Carlos Jorge", group: "B" },
  { name: "Roberto Lopes", group: "ZZZ" },
  { name: "Isabella Coelho", group: "ZZZ" },
  { name: "Aécio de Mattos", group: "C" },
  { name: "Cristina Pimenta", group: "C" },
  { name: "Natália Mattos", group: "C" },
  { name: "Tadeu Alexandre", group: "C" },
  { name: "Marina Gonçalves", group: "NNN" },
  { name: "Elmo Lincoln", group: "OOO" },
  { name: "Júnia Sanchez", group: "D" },
  { name: "Leonardo Sanchez", group: "D" },
  { name: "Vitor Ferreira", group: "PPP" },
  { name: "Daphyni Oliveira", group: "PPP" },
  { name: "Igor Ferreira", group: "QQQ" },
  { name: "Bianca Lucena", group: "QQQ" },
  { name: "Rodrigo Gonçalves", group: "E" },
  { name: "Gisele Costa", group: "E" },
  { name: "Maria Cecília", group: "E" },
  { name: "Carol Rizzo", group: "RRR" },
  { name: "Gabriel Rettore", group: "RRR" },
  { name: "Camilla Rizzo", group: "SSS" },
  { name: "João Luiz", group: "SSS" },
  { name: "Cristiano Ferreira", group: "F" },
  { name: "Poliana Diniz", group: "F" },
  { name: "Raul Diniz", group: "F" },
  { name: "Mateus Diniz", group: "F" },
  { name: "Marlene", group: "NNN" },
  { name: "Geraldo Amorim", group: "G" },
  { name: "Paolette", group: "G" },
  { name: "Pedro Amorim", group: "TTT" },
  { name: "Carolina Penido", group: "TTT" },
  { name: "Lucas Amorim", group: "UUU" },
  { name: "Bárbara Muschioni", group: "UUU" },
  { name: "Carolina Amorim", group: "VVV" },
  { name: "Frederico Azevedo", group: "VVV" },
  { name: "Matheus Passos", group: "H" },
  { name: "Paula Dominguete", group: "H" },
  { name: "Gustavo Rocha", group: "I" },
  { name: "Natalia Araújo", group: "I" },
  { name: "Rodrigo Alcântara", group: "J" },
  { name: "Júlia Alves", group: "J" },
  { name: "Marcelo Novy", group: "K" },
  { name: "Maryana Fortes", group: "K" },
  { name: "Leonardo Alves", group: "L" },
  { name: "Iara Meyer", group: "L" },
  { name: "Samuel Romani", group: "M" },
  { name: "István Dénes", group: "N" },
  { name: "Tiago Mitraud", group: "N" },
  { name: "Guilherme Marchezini", group: "O" },
  { name: "Jéssica Marchezini", group: "O" },
  { name: "Thiago Machado", group: "P" },
  { name: "Raphaella Souza", group: "P" },
  { name: "Diego Lima", group: "Q" },
  { name: "Vanessa Leite", group: "Q" },
  { name: "João Gustavo", group: "R" },
  { name: "Karol Simões", group: "R" },
  { name: "Matheus Lima", group: "S" },
  { name: "Clara Sette", group: "S" },
  { name: "Ana Clara Ribeiro", group: "T" },
  { name: "Marcos Cirilo", group: "T" },
  { name: "Beatriz Mendes", group: "U" },
  { name: "Victor Azzalin", group: "V" },
  { name: "Gabriela Couto", group: "V" },
  { name: "Paulo Artur Gomes", group: "W" },
  { name: "Maria Fernanda Stefani", group: "W" },
  { name: "Gabriel Guimarães", group: "X" },
  { name: "Marina Vanetti", group: "X" },
  { name: "Alexandre Arcanjo", group: "Y" },
  { name: "Mariana Maciel", group: "Y" },
  { name: "Felipe Hanke", group: "Z" },
  { name: "Giovanna Lanza", group: "Z" },
  { name: "Lucas Leny", group: "AA" },
  { name: "Amanda Pereira", group: "AA" },
  { name: "Pedro Handan", group: "BB" },
  { name: "Laura Soares", group: "BB" },
  { name: "Danielle Gontijo", group: "CC" },
  { name: "Joyce Paiva", group: "CC" },
  { name: "Shirlei Pereira", group: "DD" },
  { name: "Wellington Matos", group: "III" },
  { name: "Gabriel Pereira", group: "DD" },
  { name: "Irani Fernandes", group: "FF" },
  { name: "Messias Rodrigues", group: "FF" },
  { name: "Sidney Pereira", group: "GG" },
  { name: "Cynthia Resende", group: "GG" },
  { name: "Luiz Felipe", group: "HHH" },
  { name: "Simaura Soares", group: "HHH" },
  { name: "Vítor Pereira", group: "GG" },
  { name: "Sirlene Rodrigues", group: "HH" },
  { name: "Ana Clara Barbosa", group: "HH" },
  { name: "Antero Rodrigues", group: "II" },
  { name: "Rosenilde Barbosa", group: "II" },
  { name: "Natália Rodrigues", group: "JJ" },
  { name: "Jadler Guimarães", group: "JJ" },
  { name: "Valéria Monteiro", group: "KK" },
  { name: "Carloman Rodrigues", group: "LL" },
  { name: "Fred Monteiro", group: "MM" },
  { name: "Carla Monteiro", group: "MM" },
  { name: "Sara Monteiro", group: "MM" },
  { name: "Bárbara Monteiro", group: "NN" },
  { name: "Ramon Quites", group: "NN" },
  { name: "Clara Monteiro", group: "NN" },
  { name: "Davi Quites", group: "NN" },
  { name: "Camila Monteiro", group: "PP" },
  { name: "Eric Brant", group: "PP" },
  { name: "Maria da Consolação", group: "QQ" },
  { name: "Luzia Rodrigues", group: "JJJ" },
  { name: "Thais Amaral", group: "RR" },
  { name: "Paulo", group: "RR" },
  { name: "Brendow Matos", group: "EE" },
  { name: "Giulia Mendonça", group: "EE" },
  { name: "Natália Barbosa", group: "SS" },
  { name: "Gabriel Veiga", group: "SS" },
  { name: "Carolina Tolentino", group: "TT" },
  { name: "Eduardo Barbosa", group: "TT" },
  { name: "Isabela Ganem", group: "LLL" },
  { name: "Vitor Ganem", group: "UU" },
  { name: "Allana Ganem", group: "UU" },
  { name: "Bruna Ziviani", group: "MMM" },
  { name: "Vinícius Ganem", group: "MMM" },
  { name: "Omar Ganem", group: "LLL" },
  { name: "Manuela Melillo", group: "VV" },
  { name: "Diogo Freitas", group: "VV" },
  { name: "Camila Resende", group: "WW" },
  { name: "Victor Gonzalez", group: "WW" },
  { name: "Clara Magalhaes", group: "XX" },
  { name: "Mariana Resende", group: "XX" },
  { name: "Beatriz Pawlow", group: "YY" },
  { name: "Rafael Rallo", group: "YY" },
  { name: "Gabriela Duarte", group: "ZZ" },
  { name: "Julio Grossi", group: "ZZ" },
  { name: "Pedro Gomes", group: "AAA" },
  { name: "Camila Moraes", group: "AAA" },
  { name: "Ana Carolina Trindade", group: "BBB" },
  { name: "Letícia Tropia", group: "BBB" },
  { name: "Bruno Guzella", group: "CCC" },
  { name: "Paulo Vitor", group: "DDD" },
  { name: "Pedro Lopes", group: "EEE" },
  { name: "Ingrid Gomes", group: "FFF" },
  { name: "Bruno Mol", group: "FFF" },
  { name: "Maria Fernanda Ribeiro", group: "GGG" },
  { name: "Gabriel Carvalho", group: "GGG" },
  { name: "Ludmilla Quirino", group: "AAAA" },
  { name: "Arthur Andrade", group: "AAAA" },
  { name: "Ewerton Maurício", group: "BBBB" },
  { name: "Raquel Raposo", group: "BBBB" },
  { name: "Irene Aparecida", group: "CCCC" },
  { name: "Luís Fernando", group: "CCCC" },
  { name: "Karine Duarte", group: "CCCC" },
  { name: "Victor Martins", group: "CCCC" },
  { name: "Leo Amaral", group: "DDDD" },
  { name: "Gabriel Drumond", group: "EEEE" },
  { name: "Daniel Nitzsche", group: "EEEE" }
];